# Generated by Django 3.2.13 on 2022-05-19 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('anexo', models.CharField(max_length=50)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo de chamado')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretaria', models.TextField(verbose_name='Nome da secretaria')),
                ('setor', models.CharField(max_length=150, verbose_name='Subsecretaria/Setor')),
                ('matricula', models.CharField(max_length=8, verbose_name='Matricula')),
                ('telefone', models.CharField(max_length=11)),
                ('ramal', models.CharField(max_length=5)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo de suporte')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('tipo_chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.tipo_chamado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado_Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_serie', models.CharField(max_length=15)),
                ('contador', models.IntegerField()),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.impressora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.tipo_chamado', verbose_name='Tipo de chamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo_suporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.tipo_suporte', verbose_name='Tipo de suporte'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
