# Generated by Django 3.2.13 on 2022-06-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='chamado_impressora',
            old_name='user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='impressora',
            old_name='user',
            new_name='create_user',
        ),
        migrations.RenameField(
            model_name='tipo_suporte',
            old_name='user',
            new_name='create_user',
        ),
        migrations.RemoveField(
            model_name='tipo_chamado',
            name='user',
        ),
        migrations.AddField(
            model_name='tipo_chamado',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chamados.usuario'),
        ),
    ]
