# Generated by Django 3.2.13 on 2022-06-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0002_auto_20220610_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_chamado',
            options={'ordering': ['tipo']},
        ),
        migrations.RemoveField(
            model_name='chamado_impressora',
            name='create_user',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado_impressora',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado'),
        ),
        migrations.AlterField(
            model_name='chamado_impressora',
            name='impressora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chamados.impressora', verbose_name='Modelo da impressora'),
        ),
        migrations.AlterField(
            model_name='chamado_impressora',
            name='n_serie',
            field=models.CharField(max_length=15, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
