# Generated by Django 3.2.13 on 2022-07-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20220610_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
            ],
        ),
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='anexos_chamados', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chamados.status'),
        ),
    ]
