# Generated by Django 3.2.13 on 2022-07-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_alter_resposta_chamado_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta_chamado',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado'),
        ),
    ]
