# Generated by Django 3.2.13 on 2022-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_alter_resposta_chamado_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='bg',
            field=models.CharField(default='', max_length=85),
        ),
    ]
