# Generated by Django 3.2.13 on 2022-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_status_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='tem_anexo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resposta_chamado',
            name='tem_anexo',
            field=models.BooleanField(default=False),
        ),
    ]
