# Generated by Django 3.2.13 on 2022-07-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_alter_resposta_chamado_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='anexo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='anexos_chamados', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='resposta_chamado',
            name='anexo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='anexos_chamados', verbose_name='Anexo'),
        ),
    ]
