# Generated by Django 3.2.13 on 2022-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_auto_20220711_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
